// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsbznsmerbjdmqwmrmxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYnpuc21lcmJqZG1xd21ybXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTYwNTMsImV4cCI6MjA3MTc3MjA1M30.2ybexhOILITydoSZnhL2nVvpEJIVhBivf7uNK5HtACw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});